### ISSUE TITLE
commentlarda like yapmaya çalışırken hata

### ISSUE THREAD

**Issue by Atanur** [Chaisser/maaslisozluk-next#19] opened 2021-02-01 12:41 UTC
![image](https://user-images.githubusercontent.com/11318583/106460056-ce636780-64a3-11eb-81c1-e5c9808c42cf.png)

**Comment by EmirBoyaci** [comment] 2021-02-01 19:04
Duplicate of #18

**Closed by EmirBoyaci** 2021-02-01 19:04 UTC
